Controllers/PaymentTermController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using DotNetFinalProject.Helpers;
using DotNetFinalProject.Models;
using DotNetFinalProject.Enums;

namespace DotNetFinalProject.Controllers
{
    public class PaymentTermController : BaseController
    {
        #region Fields
        private DotNetFinalProjectDbContext dbContext;
        private PaymentTermHelper paymentTermHelper;

        #endregion

        #region Constructors
        public PaymentTermController(DotNetFinalProjectDbContext context)
        {
            this.dbContext = context;
            this.paymentTermHelper = new PaymentTermHelper(context);
        }
        #endregion

        #region Actions
        //--------------------------------------------------------------
        // GET: Displays PaymentTerm New / List view view
        [HttpGet]
        [Route("PaymentTermNewListView")]
        public IActionResult PaymentTermNewListView()
        {
            System.Console.WriteLine("-----------------------------------PaymentTermNewListView(1)--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            setLayoutViewBag();
            PaymentTerm paymentTerm = new PaymentTerm {DiscountDays = 0, DueDays = 0, DiscountRate = 0, DiscountDateOption = DiscountDateOption.OrderDate};
            ViewBag.AllPaymentTerms = paymentTermHelper.GetAllPaymentTermsByNameAsc();

            return View("PaymentTermNewListView", paymentTerm);
        }

        //--------------------------------------------------------------
        // POST: Add new PaymentTerm to DB
        [HttpPost]
        [Route("PaymentTerm/New/Save")]
        public IActionResult PaymentTermNewSave(PaymentTerm paymentTerm)
        {
            System.Console.WriteLine("-----------------------------------PaymentTermNewSave--------------------------------------");

            bool isValid = ModelState.IsValid;
            if( isValid)
            {
                var nameInDb = dbContext.PaymentTerm.FirstOrDefault(p => p.Name == paymentTerm.Name);
                if( nameInDb != null)
                {
                    ModelState.AddModelError("Name", "Name already exists.");
                    isValid = false;
                }
            }

            if( isValid)
            {
                // Add new PaymentTerm
                DateTime now = DateTime.Now;
                paymentTerm.CreatedAt = now;
                paymentTerm.UpdatedAt = now;
                dbContext.Add(paymentTerm);
                dbContext.SaveChanges();

                return RedirectToAction("PaymentTermNewListView");
            }
            else
            {
                // New was invalid, route back to PaymentTerm New / List view
                setLayoutViewBag();
                ViewBag.AllPaymentTerms = paymentTermHelper.GetAllPaymentTermsByNameAsc();
    
                return View("PaymentTermNewListView", paymentTerm);
            }
        }

        //--------------------------------------------------------------
        // GET: Edit PaymentTerm view
        [HttpGet]
        [Route("PaymentTerm/Edit/{paymentTermSk}")]
        public IActionResult PaymentTermEdit(int paymentTermSk)
        {
            System.Console.WriteLine("-----------------------------------PaymentTermEdit--------------------------------------");
            System.Console.WriteLine($"PaymentTermSk: {paymentTermSk}");

            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            setLayoutViewBag();
            PaymentTerm paymentTerm = paymentTermHelper.GetPaymentTermBySk(paymentTermSk);
            return View("PaymentTermEdit", paymentTerm);
        }


        //--------------------------------------------------------------
        // POST: Save Edit to PaymentTerm to DB
        [HttpPost]
        [Route("PaymentTerm/Edit/Save")]
        public IActionResult PaymentTermEditSave(PaymentTerm paymentTerm)
        {
            System.Console.WriteLine("-----------------------------------UomEditSave(PaymentTerm paymentTerm):1--------------------------------------");

            bool isValid = ModelState.IsValid;
            if( isValid)
            {
                var nameInDb = (from p in dbContext.PaymentTerm
                                  where p.PaymentTermSk != paymentTerm.PaymentTermSk
                                  where p.Name == paymentTerm.Name
                                  select p).FirstOrDefault();

                if( nameInDb != null)
                {
                    ModelState.AddModelError("Name", "Name already exists.");
                    isValid = false;
                }
            }

            if( isValid)
            {
                // Save PaymentTerm
                DateTime now = DateTime.Now;
                paymentTerm.UpdatedAt = now;
                dbContext.Update(paymentTerm);
                dbContext.SaveChanges();

                return RedirectToAction("PaymentTermNewListview");
            }

            // Edit was invalid, route back to PaymentTerm Edit view
            setLayoutViewBag();
            return View("PaymentTermEdit", paymentTerm);
        }

        //--------------------------------------------------------------
        // Get: Delete the passed PaymentTerm (ref. by paymentTermSk) from DB
        [HttpGet]
        [Route("PaymentTerm/Delete/{paymentTermSk}")]
        public IActionResult PaymentTermDelete(int paymentTermSk)
        {
            System.Console.WriteLine("-----------------------------------PaymentTermDelete--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            bool isDeleteOk = true;
            PaymentTerm paymentTermInDb = paymentTermHelper.GetPaymentTermBySk(paymentTermSk);
            if( paymentTermInDb == null)
            {
                // PaymentTerm not found in Db.  This is an exception...
                isDeleteOk = false;
            }

            if( isDeleteOk)
            {
                System.Console.WriteLine("-----------------------------------PaymentTermDelete-IsDeleteOk=true-------------------------------------");

                // Delete PaymentTerm
                dbContext.PaymentTerm.Remove(paymentTermInDb);
                dbContext.SaveChanges();
            }
            else
            {
                System.Console.WriteLine("-----------------------------------PaymentTermDelete-IsDeleteOk=false-------------------------------------");
            }
            return RedirectToAction("PaymentTermNewListView");
        }
        #endregion

        #region Methods
        #endregion
    }
}

Controllers/UomController.cs
//extern alias MySqlConnectorAlias;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using DotNetFinalProject.Helpers;
using DotNetFinalProject.Models;

namespace DotNetFinalProject.Controllers
{
    public class UomController : BaseController
    {
        #region Fields
        private DotNetFinalProjectDbContext dbContext;
        private UomHelper uomHelper;
        private UomTypeHelper uomTypeHelper;
        private IConfiguration configuration;
        #endregion

        #region Constructors
        public UomController(DotNetFinalProjectDbContext context, IConfiguration configuration)
        {
            this.dbContext = context;
            this.uomHelper = new UomHelper(context);
            this.uomTypeHelper = new UomTypeHelper(context);
            this.configuration = configuration;
        }
        #endregion

        #region Actions
        //--------------------------------------------------------------
        // GET: Displays Uom New / List view view
        [HttpGet]
        [Route("UomNewListView")]
        public IActionResult UomNewListView()
        {
            System.Console.WriteLine("-----------------------------------UomNewListView(1)--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            setLayoutViewBag();
            Uom uom = new Uom {UomTypeSk = 2};
            ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc();
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();

            AllUoms();

            return View("UomNewListView", uom);
        }

        //--------------------------------------------------------------
        // GET: Returns a JSON object containing all uoms
        [HttpGet]
        [Route("AllUoms")]
        public IActionResult AllUoms()
        {
            System.Console.WriteLine("-----------------------------------AllUoms(1)--------------------------------------");
            List<Uom> allUoms = uomHelper.GetAllUomsByUomIdAsc();

            System.Console.WriteLine("-----------------------------------AllUoms(2)--------------------------------------");
            IActionResult ajax_allUoms = Json(allUoms);
            System.Console.WriteLine(ajax_allUoms);
            System.Console.WriteLine("-----------------------------------AllUoms(3)--------------------------------------");

            return ajax_allUoms;
        }

        //--------------------------------------------------------------
        // POST: Add new Uom to DB
        [HttpPost]
        [Route("Uom/New/Save")]
        public IActionResult UomNewSave(Uom uom)
        {
            System.Console.WriteLine("-----------------------------------UomNewSave--------------------------------------");

            bool isValid = ModelState.IsValid;
            if( isValid)
            {
                var uomIdInDb = dbContext.Uom.FirstOrDefault(u => u.UomId == uom.UomId);
                if( uomIdInDb != null)
                {
                    ModelState.AddModelError("UomId", "Uom Id already exists.");
                    isValid = false;
                }
                else {
                    var uomNameInDb = dbContext.Uom.FirstOrDefault(u => u.UomName == uom.UomName);
                    if( uomNameInDb != null)
                    {
                        ModelState.AddModelError("UomName", "Uom Name already exists.");
                        isValid = false;
                    }
                }
            }

            if( isValid)
            {
                // Add new Uom
                DateTime now = DateTime.Now;
                uom.CreatedAt = now;
                uom.UpdatedAt = now;
                dbContext.Add(uom);
                dbContext.SaveChanges();

                // Add the 1-1 Uom Conversion row for the new Uom
                var uomInDb = dbContext.Uom.FirstOrDefault(u => u.UomId == uom.UomId);
                UomConversion uomConversion = new UomConversion { UomTypeSk = uomInDb.UomTypeSk, ConvertFromUomSk = uomInDb.UomSk, ConvertToUomSk = uomInDb.UomSk, ConversionFactor = 1, CreatedAt = now, UpdatedAt = now};
                dbContext.Add(uomConversion);
                dbContext.SaveChanges();

                return RedirectToAction("UomNewListView");
            }
            else
            {
                // New was invalid, route back to Uom New / List view
                setLayoutViewBag();
                ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc();
                ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
    
                return View("UomNewListView", uom);
            }
        }

        //--------------------------------------------------------------
        // GET: Edit Uom view
        [HttpGet]
        [Route("Uom/Edit/{uomSk}")]
        public IActionResult UomEdit(int uomSk)
        {
            System.Console.WriteLine("-----------------------------------UomEdit--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            setLayoutViewBag();
            Uom uom = uomHelper.GetUomBySk(uomSk);
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
            return View("UomEdit", uom);
        }


        //--------------------------------------------------------------
        // POST: Save Edit to Uom to DB
        [HttpPost]
        [Route("Uom/Edit/Save")]
        public IActionResult UomEditSave(Uom uom)
        {
            System.Console.WriteLine("-----------------------------------UomEditSave(Uom uom):1--------------------------------------");

            bool isValid = ModelState.IsValid;
            if( isValid)
            {
                var uomIdInDb = (from u in dbContext.Uom
                                  where u.UomSk != uom.UomSk
                                  where u.UomId == uom.UomId
                                  select u).FirstOrDefault();

                if( uomIdInDb != null)
                {
                    ModelState.AddModelError("UomId", "Uom Id already exists.");
                    isValid = false;
                }
                else
                {
                    var uomNameInDb = (from u in dbContext.Uom
                                        where u.UomSk != uom.UomSk
                                        where u.UomName == uom.UomName
                                        select u).FirstOrDefault();

                    if( uomNameInDb != null)
                    {
                        ModelState.AddModelError("UomName", "Uom Name already exists.");
                        isValid = false;
                    }
                }
            }

            if( isValid)
            {
                // Save uom
                DateTime now = DateTime.Now;
                uom.UpdatedAt = now;
                dbContext.Update(uom);
                dbContext.SaveChanges();

                return RedirectToAction("UomNewListview");
            }

            // Edit was invalid, route back to Uom Edit view
            setLayoutViewBag();
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
            return View("UomEdit", uom);
        }

        //--------------------------------------------------------------
        // Get: Delete the passed Uom (ref. by uomSk) from DB
        [HttpGet]
        [Route("Uom/Delete/{uomSk}")]
        public IActionResult UomDelete(int uomSk)
        {
            System.Console.WriteLine("-----------------------------------UomDelete--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            bool isDeleteOk = true;
            Uom uomInDb = uomHelper.GetUomBySk(uomSk);
            if( uomInDb == null)
            {
                // Uom not found in Db.  This is an exception...
                isDeleteOk = false;
            }

            if( isDeleteOk)
            {
                System.Console.WriteLine("-----------------------------------UomDelete-IsDeleteId=true-------------------------------------");
    
                // Delete Uom
                dbContext.Uom.Remove(uomInDb);
                dbContext.SaveChanges();
            }
            else
            {
                System.Console.WriteLine("-----------------------------------UomDelete-IsDeleteId=false-------------------------------------");
            }
            // return Json(true, JsonRequestBehavior.AllowGet);
            return RedirectToAction("UomNewListView");
        }


        //--------------------------------------------------------------
        // Get: Load Standard Units of Measure and Unit Conversions
        [HttpGet]
        [Route("Uom/LoadData")]
        public IActionResult UomLoadData()
        {
            System.Console.WriteLine("-----------------------------------UomLoadData:1--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            // Load Data 
            uomHelper.UomLoadData(configuration);

            return RedirectToAction("UomNewListView");
        }
        #endregion

        #region Methods
        #endregion
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap library -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <!-- JQuery Javascript -->
    <!-- <script src="https://code.jquery.com/jquery-1.10.2.js"></script> -->

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->


    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">   
    
    <!-- Local Style Sheet -->
    <link rel="stylesheet" type="text/css" media="screen" href="~/css/site.css" />

    <!-- <script src="main.js"></script> -->
    <!-- https://www.codeproject.com/Tips/891309/Custom-Confirmation-Box-using-Bootstrap-Modal-Dial -->
    <!-- http://www.dotnetqueries.com/Article/84/show-confirmation-message-before-delete-using-bootstrap-modal-popup-in-asp-net-mvc -->
    <script>
        $(document).ready(function () {
            // Start Document Ready function
            // Declare global variable to hold primary key value.
            var pkValue;
            $('.delete-prompt').click(function () {
                pkValue = $(this).attr('id');
                console.log("delete-prompt->click");
                $('#myModal').modal('show');
            });

            $('.delete-confirm').click(function () {
                if (pkValue != '') {
                    // Hide modal delete popup
                    $('#myModal').modal('hide');

                    // Delete the selected row
                    $.ajax({
                        url: `/Uom/Delete/${pkValue}`,
                        type: 'get',
                        //success: function () {
                        //    location.reload();
                        error: function (err) {
                            if (!$('.modal-header').hasClass('alert-danger')) {
                                $('.modal-header').removeClass('alert-success').addClass('alert-danger');
                                $('.delete-confirm').css('display', 'none');
                            }
                            $('.success-message').html(err.statusText);
                        }
                    });

                    // Remove child elements from tbody element
                    $("#tbody-alluoms").empty();

                    // Get alluoms after delete and display them in the tbody element
                    console.log("ajax:AllUoms:Begin");
                    $.ajax({
                        url: '@Url.Action("AllUoms", "Uom")',
                        type: "get",
                        data: { id: ''},
                        dataType: "json",
                        success: function (data) {
                            console.log("ajax:AllUoms:Success");
                        //    $.each(data, function (i, uom) {
                        //        console.log(uom);
                        //      var rows = 
                        //        "<tr>"
                        //      +    "<td"
                        //      +    "<td>" + uom.UomType.UomTypeName + "</td>"
                        //      +    "<td>" + uom.UomId + "</td>"
                        //      +    "<td>" + uom.UomName + "</td>"
                        //      +    "<td>" + uom.UomSk + "</td>"
                        //      +    "<td class='text-center'>"
                        //      +        "<a href=/Uom/Edit/" + uom.UomSk + ">Edit</a>"
                        //      +        "<span>|</span>"
                        //      +        "<a class='delete-prompt' href='javascript:void(0)' id='" + uom.UomSk + "'>Delete</a>"
                        //      +    "</td>"
                        //      + "</tr>"
                        //      $("#tbody-alluoms").append(rows);
                        //    });
                        }, error: function (xhr, ajaxOptions, thrownError) {
                            alert("Error");
                            console.log(xhr.status);
                            console.log(ajaxOptions);
                            console.log(thrownError);
                        }
                    });

                }
            });
            // End of the docuement ready function
        });
    </script>

</head>
<body>
    <div class="container">

    <!-- Main: Begin -->
        <div class="row">
            <div class="col-sm-12 col-md-1 col-lg-1"></div>
            <div class="col-sm-12 col-md-10 col-lg-10 bt-box bt-box-4">

                <!-- Header: Begins -->
                <div class="row border-bottom-4">
                    <!-- Nav bar -->
                    <div class="col-sm-12 col-md-8 col-lg-8 mt-8">
                        <div>
                            <a asp-controller="Home" asp-action="Home">Home</a>
                            <span>|</span>
                            <!-- <div class="d-inline dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Transactions</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Order" asp-action="Orders">Orders</a>
                                    <a class="dropdown-item" asp-controller="Shipment" asp-action="Shipments">Shipments</a>
                                    <a class="dropdown-item" asp-controller="Invoice" asp-action="Invoices">Invoices</a>
                                </div>
                            </div>
                            <span>|</span> -->
                            <div class="d-inline dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Master Files</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="PaymentTerm" asp-action="PaymentTermNewListView">Payment Terms</a>
                                    <a class="dropdown-item" asp-controller="Uom" asp-action="UomNewListView">Units of Measure</a>
                                    <a class="dropdown-item" asp-controller="UomConversion" asp-action="UomConversionNewListView">Unit Conversions</a>
                                </div>
                            </div>
                            <!-- <span>|</span>
                            <div class="d-inline dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Inquiry</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Order" asp-action="Orders">Orders</a>
                                    <a class="dropdown-item" asp-controller="Shipment" asp-action="Shipments">Shipments</a>
                                    <a class="dropdown-item" asp-controller="Invoice" asp-action="Invoices">Invoices</a>
                                </div>
                            </div>
                            <span>|</span>
                            <div class="d-inline dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Setup</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Setting" asp-action="Settings">Settings</a>
                                </div>
                            </div> -->
                        </div>
                    </div>

                    <!-- Logged In User -->
                    <div class="col-sm-12 col-md-2 col-lg-2 mt-2">
                        @if( ViewBag.LayoutLoggedIn == 1)
                        {
                        <div>Hi, @ViewBag.LayoutLoggedInUserFirstName</div>
                        }
                        else
                        {
                        <div>Not Logged In</div>
                        }
                    </div>

                    <!-- Login/Logout -->
                    <div class="col-sm-12 col-md-2 col-lg-2 pb-10">
                        <div class="text-right">
                            @if( ViewBag.LayoutLoggedIn == 1)
                            {
                            <form asp-controller="Login" asp-action="Logout" method="post">
                                <div class="form-actions">
                                    <button type="submit" class="btn  btn-link">Logout</button>
                                </div>
                            </form>
                            }
                            else
                            {
                            <form asp-controller="Login" asp-action="Login" method="get">
                                <div class="form-actions">
                                    <button type="submit" class="btn  btn-link">Login</button>
                                </div>
                            </form>
                            }
                        </div> 
                    </div>
                    
                </div>
                <!-- Header: Ends -->
        
                <!-- Render Body: Begins -->
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        @RenderBody()
                    </div>
                </div>
                <!-- Header: Ends -->
        
            </div>
            <div class="col-sm-12 col-md-2 col-lg-1"></div>

    </div>
</body>
</html>