Models/UomConversion.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DotNetFinalProject.Enums;

namespace DotNetFinalProject.Models
{
    [Table("uomconversions")]
    public class UomConversion
    {
        #region Properties

        [Key]
        [Required]
        public int UomConversionSk {get;set;}

        [Display(Name = "Uom Type:")]
        [ForeignKey("UomType")]
        [Required]
        public int UomTypeSk {get;set;}

        [Display(Name = "Convert From Uom:")]
        [ForeignKey("ConvertFromUom")]
        [Required]
        public int ConvertFromUomSk {get;set;}

        [Display(Name = "Convert To Uom:")]
        [ForeignKey("ConvertToUom")]
        [Required]
        public int ConvertToUomSk {get;set;}

        [Display(Name = "Conversion Factor:")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString="{0:#########.#########}")]
        [Range(0.000000001,99999999.999999999)]
        [Required]
        public decimal ConversionFactor {get;set;}

        public DateTime CreatedAt {get;set;}

        [Required]
        public DateTime UpdatedAt {get;set;}
        
        #endregion

        #region ForeignKeys

        public virtual UomType UomType { get; set; }

        public virtual Uom ConvertFromUom { get; set; }
    
        public virtual Uom ConvertToUom { get; set; }
        
        #endregion

        #region InverseProperties
        #endregion
    }

}

Controllers/UomConversionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using DotNetFinalProject.Helpers;
using DotNetFinalProject.Models;

namespace DotNetFinalProject.Controllers
{
    public class UomConversionController : BaseController
    {
        #region Fields
        private DotNetFinalProjectDbContext dbContext;
        private UomConversionHelper uomConversionHelper;
        private UomTypeHelper uomTypeHelper;
        private UomHelper uomHelper;
        private IConfiguration configuration;
        #endregion

        #region Constructors
        public UomConversionController(DotNetFinalProjectDbContext context, IConfiguration configuration)
        {
            this.dbContext = context;
            this.uomConversionHelper = new UomConversionHelper(context);
            this.uomTypeHelper = new UomTypeHelper(context);
            this.uomHelper = new UomHelper(context);
            this.configuration = configuration;
        }
        #endregion

        #region Actions
        //--------------------------------------------------------------
        // GET: Displays UomConversion New / List view view
        [HttpGet]
        [Route("UomConversionNewListView")]
        public IActionResult UomConversionNewListView()
        {
            System.Console.WriteLine("-----------------------------------Get:UomConversionNewListView():1--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            setLayoutViewBag();
            UomConversion uomConversion = new UomConversion {UomTypeSk = 2, ConversionFactor = 1};
            ViewBag.AllUomConversions = uomConversionHelper.GetUomConversionsByTypeFromToAsc();
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
            UomType uomType = uomTypeHelper.GetUomTypeBySk(2);
            ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc(uomType.UomTypeName);

            return View("UomConversionNewListView", uomConversion);
        }

        //--------------------------------------------------------------
        // POST: Displays UomConversion New / List view view
        [HttpPost]
        [Route("UomConversionNewListView")]
        public IActionResult UomConversionNewListView(UomConversion uomConversion)
        {
            System.Console.WriteLine("-----------------------------------Post:UomConversionNewListView(UomConversion uomConversion):1--------------------------------------");
            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            System.Console.WriteLine("-----------------------------------Post:UomConversionNewListView(UomConversion uomConversion):2--------------------------------------");
            
            UomType uomType = uomTypeHelper.GetUomTypeBySk(uomConversion.UomTypeSk);
            string filterText = uomType.UomTypeName;

            setLayoutViewBag();
            ViewBag.AllUomConversions = uomConversionHelper.GetUomConversionsByTypeFromToAsc();
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
            ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc(filterText);

            return View("UomConversionNewListView", uomConversion);
        }

        //--------------------------------------------------------------
        // POST: Save new UomConversion to DB
        [HttpPost]
        [Route("UomConversion/New/Save")]
        public IActionResult UomConversionNewSave(UomConversion uomConversion)
        {
            System.Console.WriteLine("-----------------------------------UomConversionNewSave(UomConversion uomConversion):1--------------------------------------");

            bool isValid = ModelState.IsValid;
            if( isValid)
            {
                var uomConversionInDb = (from u in dbContext.UomConversion
                                            where u.ConvertFromUomSk == uomConversion.ConvertFromUomSk
                                            where u.ConvertToUomSk == uomConversion.ConvertToUomSk
                                            select u).FirstOrDefault();
                if( uomConversionInDb != null)
                {
                    ModelState.AddModelError("ConvertFromUomSK", "From / To Uom conversion already exists.");
                    isValid = false;
                }
            }

            if( isValid)
            {
                // Add new UomConversion
                DateTime now = DateTime.Now;
                uomConversion.CreatedAt = now;
                uomConversion.UpdatedAt = now;
                dbContext.Add(uomConversion);
                dbContext.SaveChanges();
                dbContext.SaveChanges();

                return RedirectToAction("UomConversionNewListview");
            }
            else
            {
                System.Console.WriteLine("-----------------------------------UomConversionNewSave(UomConversion uomConversion):2--------------------------------------");
                System.Console.WriteLine($"{uomConversion.UomTypeSk}");

                // New was invalid, route back to UomConversion New / List view
                setLayoutViewBag();
                ViewBag.AllUomConversions = uomConversionHelper.GetUomConversionsByTypeFromToAsc();
                ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
                UomType uomType = uomTypeHelper.GetUomTypeBySk(uomConversion.UomTypeSk);

                System.Console.WriteLine($"{uomType.UomTypeName}");

                ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc(uomType.UomTypeName);

                return View("UomConversionNewListView", uomConversion);
            }
        }

        //--------------------------------------------------------------
        // GET: Edit UomConversion view
        [HttpGet]
        [Route("UomConversion/Edit/{uomConversionSk}")]
        public IActionResult UomConversionEdit(int uomConversionSk)
        {
            System.Console.WriteLine("-----------------------------------UomConversionEdit(int uomConversionSk):1--------------------------------------");
            System.Console.WriteLine($"uomConversionSk: {uomConversionSk}");

            if (HttpContext.Session.GetInt32("LoggedIn") != 1)
            {
                return  RedirectToAction("Login", "Login");
            }

            setLayoutViewBag();
            UomConversion uomConversion = uomConversionHelper.GetUomConversionBySk(uomConversionSk);
            ViewBag.AllUomConversions = uomConversionHelper.GetUomConversionsByTypeFromToAsc();
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
            ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc(uomConversion.UomType.UomTypeName);

            return View("UomConversionEdit", uomConversion);
        }


        //--------------------------------------------------------------
        // POST: Save Edit to UomConversion to DB
        [HttpPost]
        [Route("UomConversion/Edit/Save")]
        public IActionResult UomConversionEditSave(UomConversion uomConversion)
        {
            System.Console.WriteLine("-----------------------------------UomConversionEditSave(UomConversion uomConversion):1--------------------------------------");
            bool isValid = ModelState.IsValid;
            if( isValid)
            {
                var uomConversionInDb = (from u in dbContext.UomConversion
                                           where u.UomConversionSk != uomConversion.UomConversionSk
                                           where u.ConvertFromUomSk == uomConversion.ConvertFromUomSk
                                           where u.ConvertToUomSk == uomConversion.ConvertToUomSk
                                           select u).FirstOrDefault();

                if( uomConversionInDb != null)
                {
                    System.Console.WriteLine("-----------------------------------UomConversionEditSave(UomConversion uomConversion):2--------------------------------------");
        
                    ModelState.AddModelError("ConvertFromUomSk", "From / To Conversion already exists.");
                    isValid = false;
                }
            }

            if( isValid)
            {
                System.Console.WriteLine("-----------------------------------UomConversionEditSave(UomConversion uomConversion):3--------------------------------------");

                // Save UomConversion
                DateTime now = DateTime.Now;
                uomConversion.UpdatedAt = now;
                dbContext.Update(uomConversion);
                dbContext.SaveChanges();

                return RedirectToAction("UomConversionNewListview");
            }

            // Edit was invalid, route back to UomConversion Edit view
            setLayoutViewBag();
            ViewBag.AllUomConversions = uomConversionHelper.GetUomConversionsByTypeFromToAsc();
            ViewBag.AllUomTypes = uomTypeHelper.GetAllUomTypes();
            UomType uomType = uomTypeHelper.GetUomTypeBySk(uomConversion.UomTypeSk);
            ViewBag.AllUoms = uomHelper.GetAllUomsByUomIdAsc(uomType.UomTypeName);

            return View("UomConversionEdit", uomConversion);
        }

        //--------------------------------------------------------------
        // GET: Delete the passed UomConversion (ref. by UomConversionSk) from DB
        [HttpGet]
        [Route("UomConversion/Delete/{uomConversionSk}")]
        public IActionResult UomConversionDelete(int uomConversionSk)
        {
            System.Console.WriteLine("-----------------------------------UomConversionDelete--------------------------------------");

Views/UomConversion/UomConversionEdit.cshtml
@model UomConversion
@{
    ViewBag.LayoutLoggedIn = ViewBag.LoggedIn;
    ViewBag.LayoutLoggedInUserFirstName = ViewBag.LoggedInUserFirstName;
    ViewBag.LayoutTitle = "Uom Conversion Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mt-20 pb-10">
    <div class="row">

        <div class="col-sm-12 col-md-12 col-lg-12">

            <!-- Edit UomConversion Form Row: Begins -->
            <h4><u><strong>Edit Unit Conversion</strong></u></h4>
            <form class="mt-20" asp-controller="UomConversion" asp-action="UomConversionEditSave" method="post">

                <!-- UomConversionSk is hidden, so it will be included in the Model on post -->
                <Input type="hidden" asp-for="UomConversionSk">

                <!-- UomTypeSk is disabled, so we use a hidden tag to return its value on post -->
                <input type="hidden" name="UomTypeSk" value="@Model.UomTypeSk">

                <!-- UomTypeSk -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="UomTypeSk"></label>
                    <div>
                        <select class="form-control" asp-for="UomTypeSk" asp-items="@(new SelectList(ViewBag.AllUomTypes, "UomTypeSk", "UomTypeName"))" disabled>
                            <option>-Select a Uom Type-</option>
                        </select>
                    </div>
                    <span class="color-error" asp-validation-for="UomTypeSk"></span>
                </div>

                <!-- ConvertFromUomSk -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="ConvertFromUomSk"></label>
                    <div>
                        <select class="form-control" asp-for="ConvertFromUomSk" asp-items="@(new SelectList(ViewBag.AllUoms, "UomSk", "UomIdUomTypeName"))">
                        </select>
                    </div>
                    <span class="color-error" asp-validation-for="ConvertFromUomSk"></span>
                </div>

                <!-- ConvertToUomSk -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="ConvertToUomSk"></label>
                    <div>
                        <select class="form-control" asp-for="ConvertToUomSk" asp-items="@(new SelectList(ViewBag.AllUoms, "UomSk", "UomIdUomTypeName"))">
                        </select>
                    </div>
                    <span class="color-error" asp-validation-for="ConvertToUomSk"></span>
                </div>

                <!-- ConversionFactor -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="ConversionFactor"></label>
                    <div>
                         <input class="form-control" asp-for="ConversionFactor">
                    </div>
                    <span class="color-error" asp-validation-for="ConversionFactor"></span>
                </div>

                <!-- Actions -->
                <div class="row">
                    <div class="col-xs-5 col-sm-2 col-md-1 col-lg-1">
                        <!-- Save Button -->
                        <div class="form-actions">
                            <button type="submit" class="btn  btn-primary btn-md">Save</button>
                        </div>
                    </div>
                    <div class="col-xs-5 col-sm-2 col-md-1 col-lg-1">
                        <!-- Cancel Button -->
                        <a class="btn btn-danger btn-md" asp-controller="UomConversion" asp-action="UomConversionNewListView">Cancel</a>
                    </div>
                    <div class="col-xs-2 col-sm-8 col-md-10 col-lg-10">
            </form>
            <!-- Edit UomConversion Form Row: Begins -->

        </div>
    </div>
</div>

Views/UomConversion/UomConversionNewListView.cshtml
@model UomConversion
@{
    ViewBag.LayoutLoggedIn = ViewBag.LoggedIn;
    ViewBag.LayoutLoggedInUserFirstName = ViewBag.LoggedInUserFirstName;
    ViewBag.LayoutTitle = "Uom Conversion New/List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mt-20 pb-10">
    <div class="row">

        <!-- Add UomConversion Form (Left): Begins -->
        <div class="col-sm-12 col-md-3 col-lg-3">

            <!-- Add UomConversion Form Row: Begins -->
            <h4 class="text-center"><u><strong>Add</strong></u></h4>
            <form asp-controller="UomConversion" asp-action="UomConversionNewListView" method="post">

                <!-- UomTypeSk -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="UomTypeSk"></label>
                    <div>
                        <select class="form-control" asp-for="UomTypeSk" asp-items="@(new SelectList(ViewBag.AllUomTypes, "UomTypeSk", "UomTypeName"))"></select>
                    </div>
                    <span class="color-error" asp-validation-for="UomTypeSk"></span>
                </div>

                <!-- ConversionFactor -->
                <input type="hidden" name="ConversionFactor" value="@Model.ConversionFactor">

                <!-- Submit Button -->
                <div class="form-actions text-right">
                    <button type="submit" class="btn  btn-primary btn-md">Submit</button>
                </div>
            </form>


            <!-- Add UomConversion Form Row: Begins -->
            <form class="mt-20" asp-controller="UomConversion" asp-action="UomConversionNewSave" method="post">

                <!-- UomTypeSk -->
                <input type="hidden" name="UomTypeSk" value="@Model.UomTypeSk">

                <!-- ConvertFromUomSk -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="ConvertFromUomSk"></label>
                    <div>
                        <select class="form-control" asp-for="ConvertFromUomSk" asp-items="@(new SelectList(ViewBag.AllUoms, "UomSk", "UomIdUomTypeName"))">
                            <option>-Select a From Uom-</option>
                        </select>
                    </div>
                    <span class="color-error" asp-validation-for="ConvertFromUomSk"></span>
                </div>

                <!-- ConvertToUomSk -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="ConvertToUomSk"></label>
                    <div>
                        <select class="form-control" asp-for="ConvertToUomSk" asp-items="@(new SelectList(ViewBag.AllUoms, "UomSk", "UomIdUomTypeName"))">
                            <option>-Select a To Uom-</option>
                        </select>
                    </div>
                    <span class="color-error" asp-validation-for="ConvertToUomSk"></span>
                </div>

                <!-- ConversionFactor -->
                <div class="form-group">
                    <label class="col-form-label" asp-for="ConversionFactor"></label>
                    <div>
                         <input class="form-control" asp-for="ConversionFactor">
                    </div>
                    <span class="color-error" asp-validation-for="ConversionFactor"></span>
                </div>

                <!-- Add Button -->
                <div class="form-actions text-right">
                    <button type="submit" class="btn  btn-primary btn-md">Add</button>
                </div>
            </form>

        </div>
        <!-- Add UomConversion Form (Left): Ends -->


        <!-- UomConversion Table (Right): Begins -->
        <div class="col-sm-12 col-md-9 col-lg-9 border-left-2">
            <h4 class="text-center"><u><strong>Unit Conversions</strong></u></h4>

            <!-- UomConversion Grid Row: Begins -->
            <div class="row mt-10">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div class="responsive tbl-scroll">
                        <table class="table table-bordered table-striped table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th scope="col">Type</th>
                                    <th scope="col">From</th>
                                    <th scope="col">To</th>
                                    <th scope="col">Conversion</th>
                                    <th scope="col" class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var uomConversion in @ViewBag.AllUomConversions)
                                {
                                    <tr>
                                        <td>@uomConversion.UomType.UomTypeName</td>
                                        <td>@uomConversion.ConvertFromUom.UomId</td>
                                        <td>@uomConversion.ConvertToUom.UomId</td>
                                        <td>@uomConversion.ConversionFactor</td>
                                        <td class="text-center">
                                            <a href="/UomConversion/Edit/@uomConversion.UomConversionSk">Edit</a>
                                            <span>|</span>
                                            <a href="/UomConversion/Delete/@uomConversion.UomConversionSk">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Uom Grid Row: Ends -->
        </div>
        <!-- Uom Table (Right): Ends -->

    </div>

    <div class="row mt-40">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="text-center">
                <a href="/UomConversion/LoadData"><u>Load Standard Units of Measure and Unit Conversions</u></a>
            </div>
        </div>
    </div>
</div>